// Stardima Addon — single-file bundled build (generated by build-bundle.js).
// Self-contained: no local requires, no dependencies. Run with: node index.js
(function () {
  const __realRequire = typeof require === 'function' ? require : null;
  const __defs = {
  "index.js": function (module, exports, __req) {
// Stardima → Stremio/Nuvio addon server.
// Implements the Stremio addon protocol (manifest, catalog, meta, stream)
// plus an HLS/segment proxy so playback works regardless of IP-bound tokens
// or referer checks on the upstream video hosts.

const http = __realRequire("http");
const { URL } = __realRequire("url");
const stardima = __req("lib/stardima.js");
const resolver = __req("lib/resolver.js");
const { UA, resolveHost } = __req("lib/hosts.js");

const PORT = process.env.PORT || 7000;
const ADDON_ID = 'community.stardima.ar';
const VERSION = '1.0.0';

// ---------- tiny in-memory cache ----------
const cache = new Map();
function cacheGet(key, ttlMs) {
  const e = cache.get(key);
  if (e && Date.now() - e.t < ttlMs) return e.v;
  return null;
}
function cacheSet(key, v) { cache.set(key, { v, t: Date.now() }); }

// ---------- manifest ----------
const manifest = {
  id: ADDON_ID,
  version: VERSION,
  name: 'Stardima ستارديما',
  description: 'كرتون وأنمي مدبلج ومترجم من ستارديما — catalog + streaming addon.',
  logo: 'https://stardima-s7.cartoon.com.im/storage/branding/jIilPBoS046PwawHgt3EWYa1cj01pTgbEvumphDs.png',
  background: 'https://image.tmdb.org/t/p/original/9BhczLWHd0O9qOgBzO9dWKKH01a.jpg',
  resources: ['catalog', 'meta', 'stream'],
  types: ['series', 'movie'],
  idPrefixes: ['stardima:'],
  catalogs: [
    { type: 'series', id: 'stardima-series', name: 'ستارديما · مسلسلات', extra: [{ name: 'search', isRequired: false }, { name: 'skip', isRequired: false }] },
    { type: 'movie', id: 'stardima-movies', name: 'ستارديما · أفلام', extra: [{ name: 'search', isRequired: false }, { name: 'skip', isRequired: false }] },
  ],
  behaviorHints: { adult: false, configurable: false },
};

// ---------- proxy helpers ----------
function b64url(s) { return Buffer.from(s, 'utf8').toString('base64url'); }
function unb64url(s) { return Buffer.from(s, 'base64url').toString('utf8'); }

function addonBase(req) {
  const host = req.headers['x-forwarded-host'] || req.headers.host || 'localhost';
  let proto = (req.headers['x-forwarded-proto'] || '').split(',')[0].trim();
  if (!proto) proto = /^(localhost|127\.0\.0\.1|0\.0\.0\.0)/.test(host) ? 'http' : 'https';
  return `${proto}://${host}`;
}

// fetch with a hard timeout so a hung/slow CDN edge fails fast and the player
// can fall back to the next server instead of stalling.
async function fetchT(url, opts = {}, ms = 15000) {
  const ctrl = new AbortController();
  const to = setTimeout(() => ctrl.abort(), ms);
  try { return await fetch(url, { ...opts, signal: ctrl.signal }); }
  finally { clearTimeout(to); }
}

// Build a proxied stream URL that routes through this addon.
function proxied(req, targetUrl, referer) {
  const base = addonBase(req);
  return `${base}/proxy?u=${b64url(targetUrl)}&r=${b64url(referer || '')}&t=${b64url(UA)}`;
}

// Rewrite an m3u8 playlist so every URI goes through our proxy.
function rewriteM3u8(playlistText, playlistUrl, referer) {
  const base = playlistUrl; // absolute URL of this playlist
  const lines = playlistText.split(/\r?\n/);
  const out = [];
  for (let line of lines) {
    const trimmed = line.trim();
    if (!trimmed) { out.push(line); continue; }
    if (trimmed.startsWith('#')) {
      // handle URI="..." inside tags (e.g. EXT-X-I-FRAME-STREAM-INF, EXT-X-KEY, SUBTITLES)
      line = line.replace(/URI="([^"]+)"/g, (m, uri) => {
        const abs = new URL(uri, base).href;
        return `URI="${proxiedRaw(abs, referer)}"`;
      });
      out.push(line);
      continue;
    }
    // a media/variant URI line
    const abs = new URL(trimmed, base).href;
    out.push(proxiedRaw(abs, referer));
  }
  return out.join('\n');
}
// proxy URL builder that doesn't need req (uses absolute addon base captured per-request)
let PROXY_BASE = '';
function proxiedRaw(targetUrl, referer) {
  return `${PROXY_BASE}/proxy?u=${b64url(targetUrl)}&r=${b64url(referer || '')}&t=${b64url(UA)}`;
}

// ---------- HTTP handlers ----------
function sendJson(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Cache-Control': 'no-store',
  });
  res.end(body);
}
function sendText(res, code, text, ctype) {
  res.writeHead(code, { 'Content-Type': ctype || 'text/plain; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
  res.end(text);
}

async function handleCatalog(req, res, type, id, query) {
  const search = query.search || query.query || '';
  const skip = parseInt(query.skip || '0', 10) || 0;
  const cacheKey = `cat:${type}:${id}:${search}:${skip}`;
  const cached = cacheGet(cacheKey, 10 * 60 * 1000);
  if (cached) return sendJson(res, 200, cached);
  try {
    const items = await stardima.getCatalog({ search, type, skip, limit: 5000 });
    const metas = items.map((it) => ({
      id: 'stardima:' + it.slug,
      type,
      name: it.title,
      poster: it.poster,
      posterShape: 'regular',
      description: it.description || undefined,
      releaseInfo: it.year ? String(it.year) : undefined,
    }));
    const out = { metas };
    cacheSet(cacheKey, out);
    sendJson(res, 200, out);
  } catch (e) {
    sendJson(res, 500, { metas: [], error: e.message });
  }
}

async function handleMeta(req, res, type, id) {
  // id = stardima:{slug}
  const slug = id.replace(/^stardima:/, '');
  const cacheKey = `meta:${type}:${slug}`;
  const cached = cacheGet(cacheKey, 30 * 60 * 1000);
  if (cached) return sendJson(res, 200, cached);
  try {
    let meta;
    if (type === 'movie') {
      meta = await stardima.getMovieMeta(slug);
      meta.id = 'stardima:' + slug;
      // movies: expose a single video so some clients behave; stream uses meta id
    } else {
      meta = await stardima.getSeriesMeta(slug);
      meta.id = 'stardima:' + slug;
      meta.videos = (meta.videos || []).map((v) => ({
        id: 'stardima:' + slug + ':' + v.episodeId,
        title: v.title,
        season: v.season,
        episode: v.episode,
      }));
    }
    const out = { meta };
    cacheSet(cacheKey, out);
    sendJson(res, 200, out);
  } catch (e) {
    sendJson(res, 500, { meta: null, error: e.message });
  }
}

async function handleStream(req, res, type, id) {
  PROXY_BASE = addonBase(req);
  // For series: id = stardima:{slug}:{episodeId}
  // For movie:  id = stardima:{slug}  -> need to look up its episode id
  let episodeId = null;
  const parts = id.split(':');
  if (type === 'series' && parts.length >= 3) {
    episodeId = parts[parts.length - 1];
  } else if (type === 'movie') {
    const slug = id.replace(/^stardima:/, '');
    const cacheKey = `movieep:${slug}`;
    let cached = cacheGet(cacheKey, 60 * 60 * 1000);
    if (cached) episodeId = cached;
    else {
      const m = await stardima.getMovieMeta(slug);
      episodeId = m.movieEpisodeId || null;
      if (episodeId) cacheSet(cacheKey, episodeId);
    }
  } else if (type === 'series' && parts.length === 2) {
    const slug = parts[1];
    const m = await stardima.getSeriesMeta(slug);
    if (m.videos && m.videos[0]) episodeId = m.videos[0].episodeId;
  }

  if (!episodeId) return sendJson(res, 200, { streams: [] });

  // Cache the SERVER LIST (stable per episode), not the m3u8 (short-lived).
  const cacheKey = `servers:${episodeId}`;
  let result = cacheGet(cacheKey, 10 * 60 * 1000);
  if (!result) {
    try { result = await resolver.getServers(episodeId); }
    catch (e) { return sendJson(res, 200, { streams: [], error: e.message }); }
    if (!result.blocked) cacheSet(cacheKey, result);
  }

  if (result.blocked) {
    const msg = result.reason === 'login_required' ? 'يتطلب تسجيل الدخول' : 'يتطلب عضوية VIP';
    return sendJson(res, 200, { streams: [{ name: 'Stardima', title: msg, externalUrl: stardima.BASE + '/membership' }] });
  }

  // One Stremio stream per server. The url points at our /proxy/embed endpoint,
  // which resolves the actual m3u8/mp4 FRESH when the player requests it.
  const streams = (result.servers || []).map((srv) => ({
    name: `Stardima · ${srv.name}`,
    title: `${srv.name}${srv.is_vip ? ' (VIP)' : ''}`,
    url: `${PROXY_BASE}/proxy/embed?u=${b64url(srv.embedUrl)}&n=${b64url(srv.name)}`,
    behaviorHints: { notWebReady: true },
  }));
  sendJson(res, 200, { streams });
}

// ---------- diagnostics: show what THIS host sees (direct vs worker relay) ----------
async function handleDebug(req, res) {
  const W = 'https://stardima-proxy.ingots-18joist.workers.dev';
  const out = { host: 'render-or-local', ts: new Date().toISOString() };
  try { const r = await fetch(stardima.BASE + '/', { headers: { 'User-Agent': 'Mozilla/5.0' } }); out.direct_root = r.status; }
  catch (e) { out.direct_root = 'ERR ' + e.message; }
  try { const r = await fetch(W + '/', {}); out.worker_root = r.status; }
  catch (e) { out.worker_root = 'ERR ' + e.message; }
  try { const r = await fetch(W + '/search?query=naruto', { headers: { 'X-Requested-With': 'XMLHttpRequest', 'Accept': 'application/json' } }); out.worker_search = r.status; }
  catch (e) { out.worker_search = 'ERR ' + e.message; }
  sendJson(res, 200, out);
}

// ---------- proxy: resolve a host EMBED fresh at playback time ----------
// The upstream m3u8 token is short-lived, so we resolve it the moment the
// player asks, then immediately fetch + rewrite the master playlist.
async function handleProxyEmbed(req, res, query) {
  const embedUrl = unb64url(query.u || '');
  if (!embedUrl) return sendText(res, 400, 'missing embed');
  PROXY_BASE = addonBase(req);
  // The upstream CDN load-balances across many edges; some intermittently 403.
  // Re-resolving the embed yields a fresh token/edge, so retry a few times.
  const MAX_TRIES = 4;
  let lastStatus = 0;
  for (let attempt = 0; attempt < MAX_TRIES; attempt++) {
    try {
      const r = await resolveHost(embedUrl); // fetch embed, unpack, extract m3u8/mp4 (fresh)
      if (!r || !r.url) { lastStatus = 404; continue; }
      if (r.type === 'hls') {
        const upstream = await fetchT(r.url, { headers: { 'User-Agent': UA, Referer: r.referer, Accept: '*/*' } }, 12000);
        lastStatus = upstream.status;
        if (!upstream.ok) continue; // try a fresh edge
        const text = await upstream.text();
        const rewritten = rewriteM3u8(text, r.url, r.referer);
        res.writeHead(200, { 'Content-Type': 'application/vnd.apple.mpegurl', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' });
        return res.end(rewritten);
      }
      // mp4: stream bytes through (fresh fetch with referer)
      return pipeUpstream(req, res, r.url, r.referer);
    } catch (e) {
      lastStatus = 502;
    }
  }
  return sendText(res, lastStatus || 502, 'could not resolve a working stream edge (last status ' + lastStatus + ')');
}

// ---------- proxy: fetch an absolute url (variant playlist / segment / mp4) ----------
async function handleProxy(req, res, query) {
  const target = unb64url(query.u || '');
  const referer = query.r ? unb64url(query.r) : undefined;
  if (!target) return sendText(res, 400, 'missing target');
  try {
    const upstream = await fetchT(target, {
      headers: { 'User-Agent': UA, ...(referer ? { Referer: referer } : {}), 'Accept': '*/*' },
      redirect: 'follow',
    }, 15000);
    if (!upstream.ok) return sendText(res, upstream.status, 'upstream ' + upstream.status);
    const ctype = upstream.headers.get('content-type') || '';
    const isPlaylist = /\.m3u8(\?|$)/i.test(target) || /mpegurl/i.test(ctype);
    if (isPlaylist) {
      const text = await upstream.text();
      PROXY_BASE = addonBase(req);
      const rewritten = rewriteM3u8(text, target, referer);
      res.writeHead(200, { 'Content-Type': 'application/vnd.apple.mpegurl', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' });
      return res.end(rewritten);
    }
    // segment / mp4 bytes
    res.writeHead(200, {
      'Content-Type': ctype || 'application/octet-stream',
      'Access-Control-Allow-Origin': '*',
      'Accept-Ranges': 'bytes',
      'Cache-Control': /video|mpegurl/i.test(ctype) ? 'max-age=3600' : 'no-store',
    });
    const buf = Buffer.from(await upstream.arrayBuffer());
    return res.end(buf);
  } catch (e) {
    return sendText(res, 502, 'proxy error: ' + e.message);
  }
}

// Stream an upstream file (mp4) through to the client, preserving range requests.
async function pipeUpstream(req, res, url, referer) {
  const headers = { 'User-Agent': UA, ...(referer ? { Referer: referer } : {}) };
  if (req.headers.range) headers.Range = req.headers.range;
  const upstream = await fetchT(url, { headers, redirect: 'follow' }, 30000);
  if (!upstream.ok && upstream.status !== 206) return sendText(res, upstream.status, 'upstream ' + upstream.status);
  const h = {};
  for (const k of ['content-type', 'content-length', 'content-range', 'accept-ranges']) {
    const v = upstream.headers.get(k); if (v) h[k] = v;
  }
  res.writeHead(upstream.status, { ...h, 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=3600' });
  const buf = Buffer.from(await upstream.arrayBuffer());
  res.end(buf);
}

// ---------- router ----------
const server = http.createServer(async (req, res) => {
  try {
    const u = new URL(req.url, 'http://localhost');
    const path = u.pathname.replace(/\.json$/, '');
    const query = Object.fromEntries(u.searchParams.entries());

    if (req.method === 'OPTIONS') {
      res.writeHead(204, { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*', 'Access-Control-Allow-Methods': 'GET,OPTIONS' });
      return res.end();
    }

    if (path === '/' || path === '/index.html') {
      return sendText(res, 200, installPage(req), 'text/html; charset=utf-8');
    }
    if (path === '/manifest.json' || path === '/manifest') {
      return sendJson(res, 200, manifest);
    }
    if (path === '/debug') {
      return handleDebug(req, res);
    }
    if (path === '/proxy/embed') {
      return handleProxyEmbed(req, res, query);
    }
    if (path === '/proxy') {
      return handleProxy(req, res, query);
    }
    let m;
    if ((m = path.match(/^\/catalog\/([^/]+)\/([^/]+)$/))) {
      return handleCatalog(req, res, m[1], m[2], query);
    }
    if ((m = path.match(/^\/meta\/([^/]+)\/([^/]+)$/))) {
      return handleMeta(req, res, m[1], decodeURIComponent(m[2]));
    }
    if ((m = path.match(/^\/stream\/([^/]+)\/([^/]+)$/))) {
      return handleStream(req, res, m[1], decodeURIComponent(m[2]));
    }
    return sendJson(res, 404, { error: 'not found', path });
  } catch (e) {
    return sendJson(res, 500, { error: e.message });
  }
});

function installPage(req) {
  const base = addonBase(req);
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Stardima Addon</title>
<style>
body{font-family:system-ui,'Segoe UI',Tahoma,sans-serif;background:#0f1115;color:#e7e9ee;margin:0;padding:32px;line-height:1.7}
.card{max-width:720px;margin:0 auto;background:#171a21;border:1px solid #262b36;border-radius:16px;padding:28px}
h1{font-size:24px;margin:0 0 4px} .sub{color:#9aa3b2;margin:0 0 20px}
code{background:#0b0d12;border:1px solid #262b36;border-radius:8px;padding:10px 12px;display:block;word-break:break-all;direction:ltr;text-align:left;color:#7fd1ff;font-size:13px}
.btn{display:inline-block;margin-top:14px;background:#2563eb;color:#fff;text-decoration:none;padding:10px 18px;border-radius:10px;font-weight:600}
ul{padding-inline-start:20px} li{margin:6px 0}
.tag{display:inline-block;background:#1f2937;color:#9aa3b2;border-radius:999px;padding:2px 10px;font-size:12px;margin-inline-end:6px}
</style></head><body><div class="card">
<h1>🎬 Stardima Addon</h1>
<p class="sub">أدئون ستارديما لـ Stremio / Nuvio — كتالوج + بث</p>
<p>رابط التثبيت (manifest):</p>
<code id="mf">${base}/manifest.json</code>
<a class="btn" href="${base}/manifest.json">افتح الـ manifest</a>
<p style="margin-top:22px"><b>طريقة التثبيت:</b></p>
<ul>
<li><b>Stremio:</b> افتح الرابط في المتصفح → يظهر زر Install، أو الصق الرابط في Web addon.</li>
<li><b>Nuvio:</b> Settings → Content & Discovery → Addons → الصق رابط الـ manifest.</li>
</ul>
<p style="margin-top:18px"><span class="tag">series</span><span class="tag">movie</span><span class="tag">search</span><span class="tag">HLS proxy</span></p>
<p style="color:#6b7280;font-size:12px;margin-top:20px">ملاحظة: بعض الحلقات محمية بـ VIP/تسجيل دخول على ستارديما، وهذي ما بيرجع لها بث.</p>
</div></body></html>`;
}

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Stardima addon listening on 0.0.0.0:${PORT}`);
  console.log(`Manifest: http://0.0.0.0:${PORT}/manifest.json`);
});

  },
  "lib/stardima.js": function (module, exports, __req) {
// Stardima site client: catalog scraping, show meta, seasons, episodes,
// and episode stream-link lookup. All endpoints reverse-engineered from the
// site's own frontend (Laravel + Inertia).

const BASE = process.env.STARDIMA_BASE || 'https://stardima-s7.cartoon.com.im';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

// Full browser-like header sets. Cloudflare/front-ends often 403 requests from
// datacenter IPs (Render etc.) that look like bots; a complete, realistic header
// set is the first line of defence.
function htmlHeaders(referer) {
  return {
    'User-Agent': UA,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.9,ar;q=0.8',
    'Cache-Control': 'no-cache',
    'Pragma': 'no-cache',
    'Sec-Ch-Ua': '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': referer ? 'same-origin' : 'none',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    ...(referer ? { 'Referer': referer } : { 'Referer': BASE + '/' }),
  };
}
function ajaxHeaders(referer) {
  return {
    'User-Agent': UA,
    'Accept': 'application/json, text/javascript, */*; q=0.01',
    'Accept-Language': 'en-US,en;q=0.9,ar;q=0.8',
    'X-Requested-With': 'XMLHttpRequest',
    'Sec-Ch-Ua': '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Referer': referer || BASE + '/',
  };
}

// If a cloud host's IP is blocked by Stardima/Cloudflare (403), automatically
// fall back to the user's Cloudflare Worker relay (clean CF edge IP). This makes
// the addon work on Render etc. with NO environment configuration.
const WORKER_FALLBACK = (process.env.STARDIMA_RELAY || 'https://stardima-proxy.ingots-18joist.workers.dev').replace(/\/+$/, '');

async function smartFetch(path, headers) {
  let res;
  try { res = await fetch(BASE + path, { headers }); }
  catch (e) { res = null; }
  if (res && res.ok) return res;
  const blocked = !res || res.status === 403 || res.status === 429 || res.status === 503;
  if (blocked && WORKER_FALLBACK) {
    try {
      const r2 = await fetch(WORKER_FALLBACK + path, { headers });
      if (r2.ok) return r2;
    } catch (e) { /* fall through to original error */ }
  }
  if (!res) throw new Error('network error for ' + path);
  return res;
}

async function getJson(path, referer) {
  const res = await smartFetch(path, ajaxHeaders(referer));
  if (!res.ok) throw new Error('HTTP ' + res.status + ' for ' + path);
  return res.json();
}
async function getHtml(path, referer) {
  const res = await smartFetch(path, htmlHeaders(referer));
  if (!res.ok) throw new Error('HTTP ' + res.status + ' for ' + path);
  return res.text();
}

function decodeEntities(s) {
  return (s || '')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#039;|&apos;/g, "'").replace(/&nbsp;/g, ' ')
    .replace(/\\u([\da-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .trim();
}
function metaContent(html, prop) {
  const re = new RegExp('<meta[^>]+(?:property|name)="' + prop + '"[^>]+content="([^"]*)"', 'i');
  const m = html.match(re);
  return m ? decodeEntities(m[1]) : null;
}

// ---- CATALOG ----
// The public site spreads its library across a few listing pages (homepage plus
// category pages). We union them all so the addon shows the maximum public set.
const CATALOG_PAGES = ['/', '/mosalsalat', '/aflam', '/newrelases'];

function stripTags(s) { return (s || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim(); }

function scrapeCards(html) {
  const out = [];
  const anchorRe = /<a[^>]*href="[^"]*?\/(tvshow|movie)\/([a-z0-9-]+)(?:\/play\/\d+)?"[^>]*>/gi;
  let m;
  while ((m = anchorRe.exec(html)) !== null) {
    const type = m[1].toLowerCase() === 'movie' ? 'movie' : 'series';
    const slug = m[2];
    const before = html.slice(Math.max(0, m.index - 800), m.index);
    const after = html.slice(m.index, m.index + 900);
    const alts = [...before.matchAll(/alt="Poster for ([^"]*)"/gi)];
    const imgs = [...before.matchAll(/<img[^>]*src="([^"]+)"/gi)];
    let title = alts.length ? decodeEntities(alts[alts.length - 1][1]) : '';
    const poster = imgs.length ? imgs[imgs.length - 1][1] : null;
    if (!title) {
      const bh = [...before.matchAll(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/gi)];
      const ah = (after.match(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i) || [])[1];
      const h = bh.length ? bh[bh.length - 1][1] : ah;
      title = h ? decodeEntities(stripTags(h)) : '';
    }
    const clean = (title || '').trim();
    const noEp = clean.replace(/\s*-?\s*حلقة\s*\d+$/, '').trim();
    out.push({ id: type + ':' + slug, type, slug, title: (!noEp || /^شاهد/.test(noEp)) ? slug : noEp, poster });
  }
  return out;
}

// Full-library paginated catalog. The site's listing pages expose an AJAX JSON
// endpoint: GET /mosalsalat?page=N (or /aflam) with X-Requested-With returns
// { pagination:{last_page}, videos:[...] } with 15 items per page. We serve any
// [skip, skip+limit) window lazily and cache each upstream page.
const LIST_ENDPOINT = { series: '/mosalsalat', movie: '/aflam' };
const PAGE_SIZE = 15;
const _pageCache = new Map();
const PAGE_TTL = 6 * 60 * 60 * 1000;

function pageCacheGet(ep, p) {
  const e = _pageCache.get(ep + ':' + p);
  if (e && Date.now() - e.t < PAGE_TTL) return e.v;
  return null;
}
function pageCacheSet(ep, p, v) { _pageCache.set(ep + ':' + p, { v, t: Date.now() }); }
const _lastPage = new Map();

async function fetchPage(ep, p) {
  let vids = pageCacheGet(ep, p);
  if (vids) return vids;
  try {
    const data = await getJson(ep + '?page=' + p, BASE + ep);
    vids = (data && data.videos) || [];
    if (data && data.pagination && data.pagination.last_page) _lastPage.set(ep, data.pagination.last_page);
    pageCacheSet(ep, p, vids);
  } catch (e) { vids = []; }
  return vids;
}

// Fetch EVERY page of a listing (chunked concurrency) -> full library list.
async function getFull(ep, t) {
  await fetchPage(ep, 1);
  const last = _lastPage.get(ep) || 1;
  const pages = [];
  for (let p = 2; p <= last; p++) pages.push(p);
  for (let i = 0; i < pages.length; i += 20) {
    const chunk = pages.slice(i, i + 20);
    await Promise.all(chunk.map((p) => fetchPage(ep, p)));
  }
  const items = [];
  for (let p = 1; p <= last; p++) {
    for (const v of (pageCacheGet(ep, p) || [])) items.push(videoToItem(v, t));
  }
  return items;
}

function videoToItem(v, fallbackType) {
  const um = (v.url || '').match(/\/(tvshow|movie)\/([a-z0-9-]+)/i);
  const type = v.is_series ? 'series' : (um ? (um[1].toLowerCase() === 'movie' ? 'movie' : 'series') : fallbackType);
  const slug = um ? um[2] : String(v.id);
  return {
    id: type + ':' + slug, type, slug,
    title: decodeEntities(v.title || ''),
    poster: v.poster_url || v.poster || null,
    year: v.year || undefined,
    description: decodeEntities(v.description || '') || undefined,
  };
}

async function getCatalog({ search, type, skip, limit } = {}) {
  if (search && search.trim()) return searchCatalog(search);
  const t = type === 'movie' ? 'movie' : 'series';
  const ep = LIST_ENDPOINT[t];
  skip = parseInt(skip || 0, 10) || 0;
  limit = parseInt(limit || 50, 10) || 50;
  if (limit >= 1000) {
    const all = await getFull(ep, t);
    return all.slice(skip, skip + limit);
  }
  const firstPage = Math.floor(skip / PAGE_SIZE) + 1;
  const lastPage = Math.floor((skip + limit - 1) / PAGE_SIZE) + 1;
  const startGlobal = (firstPage - 1) * PAGE_SIZE;
  const pageNos = [];
  for (let p = firstPage; p <= lastPage; p++) pageNos.push(p);
  const results = await Promise.all(pageNos.map(async (p) => {
    let vids = pageCacheGet(ep, p);
    if (!vids) {
      try {
        const data = await getJson(ep + '?page=' + p, BASE + ep);
        vids = (data && data.videos) || [];
        pageCacheSet(ep, p, vids);
      } catch (e) { vids = []; }
    }
    return vids;
  }));
  const concat = [];
  for (const vids of results) for (const v of vids) concat.push(videoToItem(v, t));
  return concat.slice(skip - startGlobal, skip - startGlobal + limit);
}

// Search via the site's JSON search endpoint.
async function searchCatalog(query) {
  const data = await getJson('/search?query=' + encodeURIComponent(query));
  const vids = (data && data.videos) || [];
  return vids.map((v) => {
    const isMovie = v.type === 'movie' || v.is_movie === 1 || v.is_movie === true;
    const type = isMovie ? 'movie' : 'series';
    const slug = v.slug || v.id;
    return {
      id: type + ':' + slug,
      type,
      slug,
      title: decodeEntities(v.title || v.name || ''),
      poster: v.poster || v.cover || (v.poster_path ? 'https://image.tmdb.org/t/p/w500' + v.poster_path : null) || undefined,
      year: v.year || v.release_year || undefined,
      description: decodeEntities(v.description || ''),
    };
  }).filter((x) => x.title);
}

// ---- META (series) ----
// show page -> title/desc/poster + first episode play link
// player page -> season ids -> /series/season/{id} -> episodes
async function getSeriesMeta(slug) {
  const showHtml = await getHtml('/tvshow/' + slug);
  const title = metaContent(showHtml, 'og:title') || decodeEntities((showHtml.match(/<title>([^<]*)<\/title>/) || [])[1] || '') || slug;
  const description = metaContent(showHtml, 'og:description') || metaContent(showHtml, 'description') || '';
  let poster = metaContent(showHtml, 'og:image');
  // first episode player link
  const playLink = showHtml.match(/\/tvshow\/[a-z0-9-]+\/play\/(\d+)/i);
  const firstEpId = playLink ? playLink[1] : null;

  const meta = {
    id: 'series:' + slug,
    type: 'series',
    name: title.split('|')[0].trim(),
    poster,
    background: poster,
    description,
    slug,
    videos: [],
  };

  if (!firstEpId) return meta;

  // player page holds the season dropdown
  const playerHtml = await getHtml('/tvshow/' + slug + '/play/' + firstEpId, BASE + '/tvshow/' + slug);
  const seasons = [];
  const seasonRe = /data-season-id="(\d+)"[^>]*data-season-number="([^"]*)"/gi;
  let sm;
  while ((sm = seasonRe.exec(playerHtml)) !== null) {
    seasons.push({ id: sm[1], label: decodeEntities(sm[2]) });
  }
  // de-dupe, keep order
  const uniq = []; const sSeen = new Set();
  for (const s of seasons) { if (!sSeen.has(s.id)) { sSeen.add(s.id); uniq.push(s); } }
  meta.seasonIds = uniq.map((s) => s.id);

  // fetch episodes for each season
  let seasonNum = 1;
  for (const s of uniq) {
    let epData;
    try { epData = await getJson('/series/season/' + s.id + '?X-Requested-With=XMLHttpRequest', BASE + '/tvshow/' + slug + '/play/' + firstEpId); }
    catch (e) { seasonNum++; continue; }
    const eps = (epData && epData.episodes) || [];
    // try to read a real season number from the label
    const numMatch = (s.label || '').match(/(\d+)/);
    const sNum = numMatch ? parseInt(numMatch[1], 10) : seasonNum;
    for (const ep of eps) {
      meta.videos.push({
        id: 'series:' + slug + ':' + ep.id,
        title: decodeEntities(ep.title || ('الحلقة ' + ep.episode_number)),
        season: sNum,
        episode: ep.episode_number,
        episodeId: ep.id,
        slug,
      });
    }
    seasonNum++;
  }
  return meta;
}

// ---- META (movie) ----
async function getMovieMeta(slug) {
  const html = await getHtml('/movie/' + slug);
  const title = metaContent(html, 'og:title') || slug;
  const description = metaContent(html, 'og:description') || metaContent(html, 'description') || '';
  const poster = metaContent(html, 'og:image');
  // movie play link -> episode id
  const playLink = html.match(/\/movie\/[a-z0-9-]+\/play\/(\d+)/i) || html.match(/\/play\/(\d+)/i);
  const epId = playLink ? playLink[1] : null;
  const meta = {
    id: 'movie:' + slug,
    type: 'movie',
    name: title.split('|')[0].trim(),
    poster, background: poster, description, slug,
  };
  if (epId) meta.movieEpisodeId = epId;
  return meta;
}

// ---- EPISODE -> stream link ----
// Returns { watch_url, download_url, can_watch, reason, series, season }
async function getEpisodeLink(episodeId) {
  const data = await getJson('/series/episode/' + episodeId, BASE + '/');
  const ep = data.episode || {};
  return {
    watch_url: ep.watch_url || null,
    download_url: ep.download_url || null,
    can_watch: ep.can_watch !== false,
    reason: ep.reason || null,
    title: decodeEntities(ep.title || ''),
    series: data.series || {},
    season: data.season || {},
  };
}

module.exports = { BASE, getCatalog, searchCatalog, getSeriesMeta, getMovieMeta, getEpisodeLink, getHtml, getJson, decodeEntities };

  },
  "lib/resolver.js": function (module, exports, __req) {
// Full stream-resolution chain:
//   Stardima episode -> watch_url (hyperwatching embed)
//   -> hyperwatching data-page: video.hashid + servers[{id,name}]
//   -> GET hyperwatching /embed/{hashid}/server/{link_id}/url  => host embed url
//   -> fetch host embed, unpack Dean Edwards packer => m3u8 / mp4
// Returns a list of playable streams (one per working server).

const stardima = __req("lib/stardima.js");
const { resolveHost, UA } = __req("lib/hosts.js");

function decodeEntities(s) {
  return (s || '').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#039;/g, "'").replace(/\\\//g, '/').trim();
}

// Parse the Inertia data-page JSON out of an HTML page.
function extractInertiaProps(html) {
  const m = html.match(/data-page="([^"]*)"/) || html.match(/data-page='([^']*)'/);
  if (!m) return null;
  try {
    const decoded = m[1]
      .replace(/&quot;/g, '"').replace(/&amp;/g, '&').replace(/&#039;/g, "'")
      .replace(/&lt;/g, '<').replace(/&gt;/g, '>');
    return JSON.parse(decoded);
  } catch (e) {
    return null;
  }
}

// Given a hyperwatching watch URL, return [{name, host embed url}] for each server.
async function getHyperwatchingServers(watchUrl) {
  let html;
  try {
    const res = await fetch(watchUrl, { headers: { 'User-Agent': UA, 'Referer': stardima.BASE + '/', 'Accept-Language': 'en-US,en;q=0.9' } });
    html = await res.text();
  } catch (e) { return []; }
  const props = extractInertiaProps(html);
  const video = props && props.props && props.props.video;
  if (!video || !video.hashid || !Array.isArray(video.servers)) return [];
  const hashid = video.hashid;
  const base = new URL(watchUrl).origin; // https://v2.hyperwatching.com
  const servers = [];
  for (const s of video.servers) {
    // Resolve the actual host embed url for this server
    try {
      const res = await fetch(`${base}/embed/${hashid}/server/${s.id}/url`, {
        headers: { 'User-Agent': UA, 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'Referer': watchUrl },
      });
      if (!res.ok) continue;
      const data = await res.json();
      if (data && data.watch_url) servers.push({ name: s.name || ('server ' + s.server_id), embedUrl: decodeEntities(data.watch_url), is_vip: !!s.is_vip });
    } catch (e) { /* skip this server */ }
  }
  return servers;
}

// Resolve all playable streams for a Stardima episode id (eager: resolves m3u8 now).
// Kept for testing/direct use. The server uses getServers() + lazy proxy instead,
// because the upstream m3u8 token must be fetched fresh at playback time.
async function resolveEpisode(episodeId) {
  const link = await stardima.getEpisodeLink(episodeId);
  if (!link.can_watch) {
    return { blocked: true, reason: link.reason, streams: [] };
  }
  if (!link.watch_url) return { blocked: false, streams: [] };

  const servers = await getHyperwatchingServers(link.watch_url);
  const streams = [];
  for (const srv of servers) {
    try {
      const r = await resolveHost(srv.embedUrl);
      if (r && r.url) {
        streams.push({ name: srv.name, url: r.url, type: r.type, referer: r.referer });
      }
    } catch (e) { /* keep trying other servers */ }
  }
  return { blocked: false, streams, title: link.title, series: link.series };
}

// Lazy variant: return the server list (name + host embed url) WITHOUT resolving
// the m3u8. The addon hands each embed url to the proxy, which resolves the
// stream fresh at playback time (the upstream token is short-lived).
async function getServers(episodeId) {
  const link = await stardima.getEpisodeLink(episodeId);
  if (!link.can_watch) return { blocked: true, reason: link.reason, servers: [] };
  if (!link.watch_url) return { blocked: false, servers: [] };
  const servers = await getHyperwatchingServers(link.watch_url);
  return { blocked: false, servers, title: link.title, series: link.series };
}

module.exports = { resolveEpisode, getServers, getHyperwatchingServers, extractInertiaProps };

  },
  "lib/hosts.js": function (module, exports, __req) {
// Generic stream extractor for the third-party video hosts that hyperwatching
// embeds (Lulustream, Mixdrop, Uqload, Goodstream/strema, Streamhg/hgcloud, etc).
// Strategy: fetch the host embed page, unpack any Dean Edwards packer, then
// search the unpacked + raw HTML for an HLS (.m3u8) or progressive (.mp4) URL.

const { unpackAll } = __req("lib/unpacker.js");

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function normalizeUrl(u) {
  if (!u) return null;
  u = u.trim().replace(/\\\//g, '/'); // unescape \/
  if (u.startsWith('//')) u = 'https:' + u;
  return u;
}

// Pull candidate stream URLs out of a blob of (unpacked) JS/HTML.
function extractCandidates(blob) {
  const found = { m3u8: [], mp4: [] };
  // Direct URLs
  for (const m of blob.matchAll(/https?:\/\/[^"'\s\\<>]+?\.m3u8[^"'\s\\<>]*/g)) found.m3u8.push(m[0]);
  for (const m of blob.matchAll(/https?:\/\/[^"'\s\\<>]+?\.mp4[^"'\s\\<>]*/g)) found.mp4.push(m[0]);
  // Protocol-relative URLs (e.g. mixdrop wurl = //host/file.mp4?...)
  for (const m of blob.matchAll(/["'(]\/\/[^"'\s\\<>]+?\.mp4[^"'\s\\<>]*/g)) found.mp4.push(normalizeUrl(m[0].slice(1)));
  for (const m of blob.matchAll(/["'(]\/\/[^"'\s\\<>]+?\.m3u8[^"'\s\\<>]*/g)) found.m3u8.push(normalizeUrl(m[0].slice(1)));
  // Common JS variable patterns
  const varPatterns = [
    /wurl\s*[:=]\s*["']([^"']+)["']/g,
    /furl\s*[:=]\s*["']([^"']+)["']/g,
    /\bfile\s*[:=]\s*["']([^"']+\.(?:m3u8|mp4)[^"']*)["']/g,
    /\bsrc\s*[:=]\s*["']([^"']+\.(?:m3u8|mp4)[^"']*)["']/g,
    /["']?(?:hls_?url|stream_?url|video_?url|playlist)["']?\s*[:=]\s*["']([^"']+\.(?:m3u8|mp4)[^"']*)["']/gi,
  ];
  for (const re of varPatterns) {
    for (const m of blob.matchAll(re)) {
      const u = normalizeUrl(m[1]);
      if (!u) continue;
      if (u.includes('.m3u8')) found.m3u8.push(u);
      else if (u.includes('.mp4')) found.mp4.push(u);
    }
  }
  found.m3u8 = [...new Set(found.m3u8.filter(Boolean))];
  found.mp4 = [...new Set(found.mp4.filter(Boolean))];
  return found;
}

// fetch with a hard timeout so a hung embed fails fast (caller can retry/next server)
async function fetchT(url, opts = {}, ms = 12000) {
  const ctrl = new AbortController();
  const to = setTimeout(() => ctrl.abort(), ms);
  try { return await fetch(url, { ...opts, signal: ctrl.signal }); }
  finally { clearTimeout(to); }
}

// Resolve a host embed URL to a playable stream.
// Returns { url, type: 'hls'|'mp4', referer } or null.
async function resolveHost(embedUrl) {
  const origin = new URL(embedUrl).origin + '/';
  let html;
  try {
    const res = await fetchT(embedUrl, {
      headers: { 'User-Agent': UA, 'Referer': 'https://v2.hyperwatching.com/', 'Accept-Language': 'en-US,en;q=0.9' },
      redirect: 'follow',
    }, 12000);
    html = await res.text();
  } catch (e) {
    return null;
  }
  const unpacked = unpackAll(html);
  const blob = unpacked + '\n' + html;
  const cand = extractCandidates(blob);

  // Prefer HLS (adaptive, what Stremio/Nuvio players handle best), then MP4.
  if (cand.m3u8.length) return { url: cand.m3u8[0], type: 'hls', referer: origin };
  if (cand.mp4.length) return { url: cand.mp4[0], type: 'mp4', referer: origin };

  // Some hosts (Goodstream via strema.top/embed2?id=REAL) wrap another embed.
  // Try to follow an inner embed URL one level deep.
  const inner = html.match(/https?:\/\/[^"'\s\\<>]+?embed[^"'\s\\<>]*/i) ||
                blob.match(/https?:\/\/(?:goodstream\.one|strema\.top)\/[^"'\s\\<>]+/i);
  if (inner && inner[0] !== embedUrl) {
    const deep = await resolveHost(inner[0]);
    if (deep) return deep;
  }
  return null;
}

module.exports = { resolveHost, extractCandidates, normalizeUrl, UA };

  },
  "lib/unpacker.js": function (module, exports, __req) {
// Robust Dean Edwards packer unpacker.
// Many video hosts (Mixdrop, Lulustream, Uqload...) hide the m3u8 inside
// eval(function(p,a,c,k,e,d){...}('payload',radix,count,'keywords',0,{}))
// We locate the full eval(...) call with string-aware paren counting, then
// evaluate the inner function-call expression to recover the original source.

function findEvalBlock(src, from = 0) {
  const start = src.indexOf('eval(function(p,a,c,k,e', from);
  if (start === -1) return null;
  // Walk from the '(' after 'eval' and count parens, skipping string literals.
  let i = src.indexOf('(', start);
  if (i === -1) return null;
  let depth = 0;
  let inStr = false;
  let strCh = '';
  for (; i < src.length; i++) {
    const ch = src[i];
    if (inStr) {
      if (ch === '\\') { i++; continue; }
      if (ch === strCh) inStr = false;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === '`') { inStr = true; strCh = ch; continue; }
    if (ch === '(') depth++;
    else if (ch === ')') {
      depth--;
      if (depth === 0) {
        // inner = everything between eval( and the matching )
        const inner = src.slice(src.indexOf('(', start) + 1, i);
        return { inner, end: i + 1 };
      }
    }
  }
  return null;
}

// Parse the four packer arguments out of the inner call expression, WITHOUT eval
// (Cloudflare Workers forbid eval/new Function).
function unescapeJS(lit) {
  let s = lit.slice(1, -1);
  return s.replace(/\\(x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|.)/g, (m, g) => {
    if (g[0] === 'x') return String.fromCharCode(parseInt(g.slice(1), 16));
    if (g[0] === 'u') return String.fromCharCode(parseInt(g.slice(1), 16));
    switch (g) {
      case 'n': return '\n'; case 't': return '\t'; case 'r': return '\r';
      case 'b': return '\b'; case 'f': return '\f'; case 'v': return '\v';
      case '0': return '\0'; default: return g; // \\ \' \" \/ etc.
    }
  });
}
function decodePacker(p, a, c, k) {
  const enc = function (cc) {
    return (cc < a ? '' : enc(parseInt(cc / a))) + ((cc = cc % a) > 35 ? String.fromCharCode(cc + 29) : cc.toString(36));
  };
  const d = {};
  let i = c;
  while (i--) d[enc(i)] = k[i] || enc(i);
  return p.replace(/\b\w+\b/g, (m) => (Object.prototype.hasOwnProperty.call(d, m) ? d[m] : m));
}
function parsePackerArgs(inner) {
  const m = inner.match(/\}\s*\(\s*('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")/);
  if (!m) return null;
  return { p: unescapeJS(m[1]), a: parseInt(m[2], 10), c: parseInt(m[3], 10), k: unescapeJS(m[4]).split('|') };
}

// Unpack the FIRST packer block found. Returns unpacked source string or null.
function unpackOnce(src, from = 0) {
  const block = findEvalBlock(src, from);
  if (!block) return null;
  try {
    const args = parsePackerArgs(block.inner);
    if (!args) return null;
    const code = decodePacker(args.p, args.a, args.c, args.k);
    if (typeof code === 'string' && code) return { code, end: block.end };
    return null;
  } catch (e) {
    return null;
  }
}

// Some pages nest multiple packers; unpack recursively (packer inside packer).
// Returns the concatenation of the original source + all unpacked layers, so
// URL searching sees everything.
function unpackAll(src, maxDepth = 5) {
  let layers = [src];
  let current = src;
  for (let d = 0; d < maxDepth; d++) {
    const r = unpackOnce(current, 0);
    if (!r || !r.code) break;
    layers.push(r.code);
    if (!/eval\(function\(p,a,c,k,e/.test(r.code)) break;
    current = r.code;
  }
  return layers.join('\n');
}

module.exports = { unpackOnce, unpackAll, findEvalBlock };

  }
  };
  const __cache = {};
  function __req(id) {
    if (__cache[id]) return __cache[id].exports;
    const def = __defs[id];
    if (!def) throw new Error('module not found: ' + id);
    const m = { exports: {} };
    __cache[id] = m;
    def(m, m.exports, __req);
    return m.exports;
  }
  __req('index.js');
})();
